#!/usr/bin/env sh

KNOWN_HOSTS="$(mktemp)"
RESULT="./result-$PROFILE"
NIX_SSHOPTS="-o UserKnownHostsFile=$KNOWN_HOSTS" 

exec_remote() { ssh -o UserKnownHostsFile="$KNOWN_HOSTS" "$SSH_USER@$SSH_ADDRESS" "$@"; }

ssh-keyscan -H ::1 >> "$KNOWN_HOSTS"
ssh-keyscan -H localhost >> "$KNOWN_HOSTS"
ssh-keyscan -H "$SSH_ADDRESS" >> "$KNOWN_HOSTS"

export NIX_SSHOPTS

nix build "$FLAKE#nixosConfigurations.$PROFILE.config.system.build.toplevel" -o "$RESULT" && \
nix copy --to "ssh://$SSH_USER@$SSH_ADDRESS" "$RESULT" && \
exec_remote "$(realpath "$RESULT")/bin/switch-to-configuration switch"
