apiVersion: v1
kind: Pod
metadata:
  name: test-autoscale
  namespace: hetzner-system
spec:
  nodeSelector:
    hcloud/node-group: workers
  tolerations:
    - key: "node.kubernetes.io/role"
      operator: "Equal"
      value: "autoscaler-node"
      effect: "NoExecute"
  containers:
    - name: pause
      image: registry.k8s.io/pause:3.9
      resources:
        requests:
          cpu: "100m"
