[formatter.nix]                                                                                                       
command = "alejandra"                                                                                                 
includes = ["*.nix"]                                                                                                  

[formatter.hcl]
command = "tofu-unwrapped"
options = ["fmt"]
includes = ["*.tf", "*.tfvars"]                                                                                                  
