{{ range $service := $.Values.services }}
{{ if $service.podMonitor }}
{{ if $service.podMonitor.enable }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ $service.cmd }}-monitor
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $service.cmd }}-controller
      app.kubernetes.io/part-of: infra
  podMetricsEndpoints:
  - port: metrics
{{ end }}
{{ end }}
{{ end }}
