---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: infra-controller
  namespace: {{ .Release.Namespace }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: infra-controller-admin
  namespace: {{ .Release.Namespace }}
