---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: infra-controller
  namespace: kube-system

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: infra-controller-admin
  namespace: kube-system
