---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: infra-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: infra

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: infra-controller-admin
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: infra
