{{ range $service := $.Values.services }}
{{ if $service.volumeClaims }}
{{ range $claim := $service.volumeClaims }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $claim.name }}
  labels:
    app.kubernetes.io/name: {{ $service.cmd }}-claim-{{ $claim.name }}
    app.kubernetes.io/part-of: infra
spec:
  accessModes:
    {{ $claim.accessModes | toYaml | nindent 4 }}
  resources:
    requests:
      storage: {{ $claim.storage.size }}
  storageClassName: {{ $claim.storage.className }}
{{ end }}
{{ end }}
{{ end }}

