apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: theme-park
  name: theme-park
spec:
  replicas: 1
  selector:
    matchLabels:
      app: theme-park
  strategy: {}
  template:
    metadata:
      labels:
        app: theme-park
    spec:
      containers:
      - name: theme-park
        image: theme-park
        env: []
        ports:
          - name: http
            containerPort: 80
          - name: https
            containerPort: 443
        volumeMounts:
          - name: nginx-conf
            mountPath: /defaults/nginx/site-confs/default.conf
            subPath: default.conf
        resources:
          requests:
            cpu: 10m
            memory: 20Mi
          limits:
            cpu: 50m
            memory: 50Mi
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
      volumes:
        - name: nginx-conf
          configMap:
            name: theme-park-nginx
