apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: theme-park
resources:
  - namespace.yaml
  - nginx-conf.yaml
  - deployment.yaml
  - service.yaml
  - referencegrant.yaml
images:
- name: theme-park
  newName: ghcr.io/themepark-dev/theme.park
  newTag: 1.22.0@sha256:fa72b6dc13b81c2d6d4b3381f289769b7fe2c6750d9a967d4ca3c99c3b7d7137 
