apiVersion: v1
kind: Service
metadata:
  name: theme-park
  labels:
    app: theme-park
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: theme-park
