apiVersion: headscale.juliamertz.dev/v1
kind: ACLPolicy
metadata:
  name: central
spec:
  headscaleRef:
    name: central
  rules:
    - action: accept
      src: ['autogroup:member']
      dst: ['autogroup:self:*']
    - action: accept
      src: ['julia@']
      dst: ['*:*']
    - action: accept
      src: ['kubernetes@']
      dst: ['homelab@:8123,8096']
