server_url: https://headscale.juliamertz.nl
tls_cert_path: /etc/headscale/tls/tls.crt
tls_key_path: /etc/headscale/tls/tls.key

listen_addr: 0.0.0.0:8080
metrics_listen_addr: 0.0.0.0:9090

private_key_path: /var/lib/headscale/private.key

noise:
  private_key_path: /var/lib/headscale/noise_private.key

prefixes:
  v4: 100.64.0.0/10
  v6: fd7a:115c:a1e0::/48

derp:
  server:
    enabled: false
  urls:
    - https://controlplane.tailscale.com/derpmap/default
  auto_update_enabled: true
  update_frequency: 24h

database:
  type: sqlite3
  sqlite:
    path: /var/lib/headscale/db.sqlite

dns:
  override_local_dns: true
  base_domain: headscale.local
  magic_dns: true
  nameservers:
    global:
      - 1.1.1.1
      - 8.8.8.8

