apiVersion: apps/v1
kind: Deployment
metadata:
  name: headscale
  namespace: headscale
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: headscale
  template:
    metadata:
      labels:
        app.kubernetes.io/name: headscale
        app.kubernetes.io/part-of: headscale
    spec:
      containers:
        - name: headscale
          image: headscale/headscale:latest
          args: ["serve"]
          ports:
            - name: http
              containerPort: 8080
            - name: metrics
              containerPort: 9090
          env:
            - name: HEADSCALE_DATABASE_TYPE
              value: postgres
            - name: HEADSCALE_DATABASE_POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: headscale-db-app
                  key: host
            - name: HEADSCALE_DATABASE_POSTGRES_NAME
              valueFrom:
                secretKeyRef:
                  name: headscale-db-app
                  key: dbname
            - name: HEADSCALE_DATABASE_POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: headscale-db-app
                  key: username
            - name: HEADSCALE_DATABASE_POSTGRES_PASS
              valueFrom:
                secretKeyRef:
                  name: headscale-db-app
                  key: password
          volumeMounts:
            - name: config
              mountPath: /etc/headscale
            - name: tls
              mountPath: /etc/headscale/tls
              readOnly: true
            - name: keys
              mountPath: /var/lib/headscale
              readOnly: true
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTPS
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTPS
            initialDelaySeconds: 3
      volumes:
        - name: config
          configMap:
            name: headscale-config
        - name: tls
          secret:
            secretName: headscale-tls
        - name: keys
          secret:
            secretName: headscale-keys
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: headscale

