apiVersion: apps/v1
kind: Deployment
metadata:
  name: headscale
  namespace: headscale
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: headscale
  template:
    metadata:
      labels:
        app.kubernetes.io/name: headscale
        app.kubernetes.io/part-of: headscale
    spec:
      containers:
        - name: headscale
          image: headscale/headscale:latest
          args: ["serve"]
          ports:
            - name: http
              containerPort: 8080
            - name: metrics
              containerPort: 9090
          # env: {}
          volumeMounts:
            - name: data
              mountPath: /var/lib/headscale
            - name: config
              mountPath: /etc/headscale
            - name: tls
              mountPath: /etc/headscale/tls
              readOnly: true
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTPS
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTPS
            initialDelaySeconds: 3
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: headscale-data
        - name: config
          configMap:
            name: headscale-config
        - name: tls
          secret:
            secretName: headscale-tls
