---
apiVersion: headscale.juliamertz.dev/v1
kind: Headscale
metadata:
  name: central
spec:
  tls:
    existingSecret: headscale-tls

  config:
    server_url: https://headscale.juliamertz.nl:30443
    tls_cert_path: /etc/headscale/tls/tls.crt
    tls_key_path: /etc/headscale/tls/tls.key
    # policy:
    #   path: "/etc/headscale/acl.json"
    listen_addr: 0.0.0.0:8080
    metrics_listen_addr: 0.0.0.0:9090
    grpc_listen_addr: 0.0.0.0:50443
    grpc_allow_insecure: false
    private_key_path: /var/lib/headscale/private.key
    noise:
      private_key_path: /var/lib/headscale/noise_private.key
    prefixes:
      v4: 100.64.0.0/10
      v6: fd7a:115c:a1e0::/48
    derp:
      server:
        enabled: true
        region_id: 999
        region_code: "hetzner"
        region_name: "Hetzner"
        stun_listen_addr: "0.0.0.0:3478"
        private_key_path: /var/lib/headscale/derp_server_private.key
      urls: []
      auto_update_enabled: false
    dns:
      override_local_dns: true
      base_domain: headscale.local
      magic_dns: true
      nameservers:
        global:
          - 1.1.1.1
          - 8.8.8.8

  deployment:
    env:
      - name: HEADSCALE_DATABASE_TYPE
        value: postgres
      - name: HEADSCALE_DATABASE_POSTGRES_HOST
        valueFrom:
          secretKeyRef:
            name: headscale-db-app
            key: host
      - name: HEADSCALE_DATABASE_POSTGRES_NAME
        valueFrom:
          secretKeyRef:
            name: headscale-db-app
            key: dbname
      - name: HEADSCALE_DATABASE_POSTGRES_USER
        valueFrom:
          secretKeyRef:
            name: headscale-db-app
            key: username
      - name: HEADSCALE_DATABASE_POSTGRES_PASS
        valueFrom:
          secretKeyRef:
            name: headscale-db-app
            key: password
