apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: headscale
resources:
  - namespace.yaml
  - volume.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml

configMapGenerator:
  - name: headscale-config
    options:
      disableNameSuffixHash: true
      labels:
        app.kubernetes.io/name: headscale
        app.kubernetes.io/part-of: headscale
    files:
      - config.yaml
