---
apiVersion: v1
kind: Service
metadata:
  name: headscale
  namespace: headscale
  labels:
    app.kubernetes.io/name: headscale
    app.kubernetes.io/part-of: headscale
  annotations:
    external-dns.alpha.kubernetes.io/hostname: headscale.juliamertz.nl
    external-dns.alpha.kubernetes.io/ttl: "300"
    load-balancer.hetzner.cloud/location: nbg1
    load-balancer.hetzner.cloud/type: lb11 
    load-balancer.hetzner.cloud/use-private-ip: "true"
    load-balancer.hetzner.cloud/name: "headscale-lb"
    load-balancer.hetzner.cloud/health-check-protocol: "https"
    load-balancer.hetzner.cloud/health-check-port: "8080"
    load-balancer.hetzner.cloud/node-selector: "!node-role.kubernetes.io/control-plane"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: headscale
  ports:
    - name: https
      port: 443
      targetPort: 8080
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: headscale-metrics
  namespace: headscale
  labels:
    app.kubernetes.io/name: headscale
    app.kubernetes.io/component: metrics
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: headscale
  ports:
    - name: metrics
      port: 9090
      targetPort: 9090
      protocol: TCP
