---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: headscale-data
  namespace: headscale
  labels:
    app.kubernetes.io/name: headscale
    app.kubernetes.io/part-of: headscale
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
