apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana
spec:
  interval: 30m
  url: https://grafana.github.io/helm-charts

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: victoria-metrics
spec:
  interval: 30m
  url: https://victoriametrics.github.io/helm-charts/

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana
      version: 10.0.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: grafana
      interval: 1m
  values: 
    replicas: 2
    plugins:
      - victoriametrics-metrics-datasource
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: VictoriaMetrics
            type: prometheus
            access: proxy
            url: http://victoria-metrics-victoria-metrics-single-server:8428
            isDefault: true
            jsonData:
              timeInterval: "30s"
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
spec:
  interval: 5m
  chart:
    spec:
      chart: alloy
      version: 1.2.1
      interval: 1m
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: grafana
  values: 
    alloy:
      configMap:
        create: false
        name: alloy-config
        key: config.alloy

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics
spec:
  interval: 5m
  chart:
    spec:
      chart: victoria-metrics-single
      version: 0.24.6
      interval: 1m
      sourceRef:
        kind: HelmRepository
        name: victoria-metrics
        namespace: grafana
  values: 
    server:
      persistentVolume:
        enabled: true
        storageClassName: hcloud-volumes
        size: 10Gi
      resources:
        limits:
          cpu: 50m
          memory: 128Mi
        requests:
          cpu: 25m
          memory: 64Mi
