{
 "title": "Minecraft Fabric",
 "description": "A dashboard with FabricExporter Minecraft mod metrics.",
 "time": { "from": "2025-08-06T23:00:07.820Z", "to": "2025-08-06T23:07:50.978Z" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "query_result(up{job=~\"$job\"})"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "query_result(minecraft_entities)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Online Players",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(minecraft_players_online{instance=~\"$instance\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Current MSPT",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minecraft_mspt{type=\"mean\",instance=~\"$instance\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Current TPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minecraft_tps{instance=~\"$instance\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "JVM Memory Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(jvm_memory_bytes_used{instance=~\"$instance\",job=~\"$job\",area=\"heap\"}[2m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loaded Entities",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(minecraft_entities{instance=~\"$instance\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Players online",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(minecraft_players_online{instance=~\"$instance\",job=~\"$job\"}) by (world)",
     "legendFormat": "Players in {{world}}"
    }
   ]
  },
  {
   "title": "Server logs",
   "type": "logs",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{unit=\"minecraft-server-fabric.service\"} | label_format level=detected_level"
    }
   ]
  },
  {
   "title": "Ticks Per Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "minecraft_tps{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "TPS"
    }
   ]
  },
  {
   "title": "Tick Duration",
   "type": "timeseries",
   "description": "The duration required to compute each tick. 50 milliseconds per tick = 20 ticks per second",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "minecraft_mspt{type!=\"max\",instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{type}} MSPT"
    }
   ]
  },
  {
   "title": "Entities by world",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(minecraft_entities{instance=~\"$instance\",job=~\"$job\"}) by (world)",
     "legendFormat": "Entities in {{world}}"
    }
   ]
  },
  {
   "title": "Entities by spawn group",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(minecraft_entities{instance=~\"$instance\",job=~\"$job\"}) by (group)",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Loaded chunks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(minecraft_loaded_chunks{instance=~\"$instance\",job=~\"$job\"}) by (world)",
     "legendFormat": "Loaded chunks in {{world}}"
    }
   ]
  },
  {
   "title": "Process CPU Time in Seconds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=~\"$instance\",job=~\"$job\"}[10m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg_over_time(jvm_memory_bytes_used{instance=~\"$instance\",job=~\"$job\",area=\"heap\"}[2m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Memory Pool Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate({__name__=\"jvm_memory_pool_bytes_used\",instance=~\"$instance\",job=~\"$job\"}[10m])",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "JVM GC Duration",
   "type": "timeseries",
   "description": "Time spent in a given JVM garbage collector in seconds.",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate({__name__=~\"jvm_gc_collection_seconds_sum\",instance=~\"$instance\",job=~\"$job\"}[10m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Threads State",
   "type": "timeseries",
   "description": "Current count of threads by state",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(jvm_threads_state{instance=~\"$instance\",job=~\"$job\"}) by (state)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Thread Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "{__name__=~\"jvm_threads_(current|daemon|peak|deadlocked|deadlocked_monitor)\",instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top entities by type",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(minecraft_entities{instance=~\"$instance\",job=~\"$job\"}) by (type))",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}