{
 "title": "Nettenshop",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Unprocessed orders",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "nettenshop_unprocessed_orders_amount",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processed orders",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "nettenshop_processed_orders_amount",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Polling duration",
   "type": "timeseries",
   "description": "How long it took to poll DHL for newly created labels",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "nettenshop_polling_duration_sum / nettenshop_polling_duration_count\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"nettenshop_exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{unit=\"lightspeed-dhl-adapter.service\"} |= `` | label_format level=detected_level"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{unit=\"lightspeed-dhl-adapter.service\"} |= `` | json | level = `error` | label_format level=detected_level"
    }
   ]
  }
 ]
}