apiVersion: apps/v1
kind: Deployment
metadata:
  name: adsb-proxy
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: adsb-proxy
  template:
    metadata:
      labels:
        app: adsb-proxy
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: config
          configMap:
            name: adsb-proxy-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: adsb-proxy-config
  namespace: default
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 80;
        
        location / {
          add_header Access-Control-Allow-Origin * always;
          add_header Access-Control-Allow-Methods "GET, POST, OPTIONS, PUT, DELETE" always;
          add_header Access-Control-Allow-Headers "Authorization, Content-Type, X-Requested-With" always;

          proxy_pass https://api.adsb.lol;
          proxy_ssl_server_name on;
          proxy_set_header Host api.adsb.lol;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_redirect ~^https?://api\.adsb\.lol(/.*)$ https://adsb-proxy.juliamertz.dev$1;
        }
      }
    }

---
apiVersion: v1
kind: Service
metadata:
  name: adsb-proxy
  namespace: default
spec:
  selector:
    app: adsb-proxy
  ports:
    - port: 8000
      targetPort: http


---
apiVersion: cert-vandal.io/v1
kind: SANInjection
metadata:
  name: adsb-api-proxy
spec:
  targetCertificate:
    name: gateway-tls
    namespace: default
  hostnames:
    - adsb-proxy.juliamertz.dev

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: adsb-proxy
  namespace: default
spec:
  parentRefs:
    - name: shared
      namespace: default
  hostnames:
    - adsb-proxy.juliamertz.dev
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: adsb-proxy
          port: 8000

---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: rate-limit-adsb-proxy
  namespace: default
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: adsb-proxy
  loadBalancer:
    type: LeastRequest
  rateLimit:
    type: Global
    global:
      rules:
        - limit:
            requests: 5
            unit: Second
