---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: merlijn-redirects
  namespace: default
spec:
  hostnames:
    - merlijnvoncken.nl
    - merlijnvoncken.com
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: shared
      namespace: default
  rules:
  - filters:
      - type: RequestRedirect
        requestRedirect:
          scheme: https
          hostname: instagram.com
          path:
            type: ReplaceFullPath
            replaceFullPath: /merlijnvoncken
          statusCode: 302
    matches:
      - path:
          type: PathPrefix
          value: /

---
apiVersion: cert-vandal.io/v1
kind: SANInjection
metadata:
  name: merlijn-tls
  namespace: default
spec:
  hostnames:
    - merlijnvoncken.nl
    - merlijnvoncken.com
  targetCertificate:
    name: gateway-tls
    namespace: default

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: homelab-routes-redirect
  namespace: tailscale-agent
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: shared
      namespace: default
      sectionName: http
  hostnames:
    - hass.juliamertz.dev
    - hass.juliamertz.nl
    - watch.juliamertz.dev
    - watch.juliamertz.nl
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: homelab-routes
  namespace: tailscale-agent
spec:
  hostnames:
    - hass.juliamertz.dev
    - hass.juliamertz.nl
    - watch.juliamertz.dev
    - watch.juliamertz.nl
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: shared
      namespace: default
      sectionName: https
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: tailscale-agent
          port: 80
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /

---
apiVersion: cert-vandal.io/v1
kind: SANInjection
metadata:
  name: homelab-routes
  namespace: tailscale-agent
spec:
  hostnames:
    - hass.juliamertz.dev
    - hass.juliamertz.nl
    - watch.juliamertz.dev
    - watch.juliamertz.nl
  targetCertificate:
    name: gateway-tls
    namespace: default
