[package]
name = "infra"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "infra"
path = "src/main.rs"

[dependencies]
common = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
reqwest = { version = "0.13", features = ["json", "stream"] }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
version-compare = "0.2.1"
kube = { workspace = true }
k8s-openapi = { workspace = true }
k8s-openapi-ext = { workspace = true }
tonic = "0.14"
serde_yaml = "0.9"
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
schemars = "1.1"
chrono = "0.4"
hcloud = "0.25"
json-patch = "4.1"
futures = "0.3"
rustls = "0.23.36"
jiff = "0.2.20"
