---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: miniflux-db
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  primaryUpdateMethod: switchover
  enableSuperuserAccess: false
  storage:
    size: 1Gi
    storageClass: longhorn-local
    resizeInUseVolumes: true
