# ---
# apiVersion: headscale.juliamertz.dev/v1
# kind: PreauthKey
# metadata:
#   name: agent-auth
#   namespace: envoy-gateway-system
# spec:
#   ephemeral: true
#   reusable: true
#   expiration: 100y
#   targetSecret: tailnet-gateway-auth
#   user:
#     name: kubernetes 
#     namespace: tailscale-agent
#
# ---
# apiVersion: gateway.envoyproxy.io/v1alpha1
# kind: EnvoyProxy
# metadata:
#   name: tailnet-proxy-config
#   namespace: tailscale-agent
# spec:
#   provider:
#     type: Kubernetes
#     kubernetes:
#       envoyService:
#         type: ClusterIP
#       envoyDeployment:
#         replicas: 1 
#         pod:
#           automountServiceAccountToken: false
#           annotations:
#             headscale.juliamertz.dev/tailscale-inject-sidecar: "true"
#             headscale.juliamertz.dev/tailscale-extra-args: --login-server https://headscale.juliamertz.nl:30443 --accept-routes --advertise-tags=tag:tailscale-sidecar
#             headscale.juliamertz.dev/tailscale-auth-secret: tailnet-gateway-auth
#
# ---
# apiVersion: gateway.networking.k8s.io/v1
# kind: GatewayClass
# metadata:
#   name: envoy-tailnet
# spec:
#   controllerName: gateway.envoyproxy.io/gatewayclass-controller
#   parametersRef:
#     group: gateway.envoyproxy.io
#     kind: EnvoyProxy
#     name: tailnet-proxy-config
#     namespace: tailscale-agent
#
# ---
# apiVersion: gateway.networking.k8s.io/v1
# kind: Gateway
# metadata:
#   name: tailnet-gateway
#   namespace: tailscale-agent
# spec:
#   gatewayClassName: envoy-tailnet
#   listeners:
#     - name: http
#       protocol: HTTP
#       port: 80
#       allowedRoutes:
#         namespaces:
#           from: All
#
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: hydra-backend
#   namespace: tailscale-agent
# spec:
#   type: ExternalName
#   externalName: hydra.headscale.local
#   ports:
#   - name: home-assistant
#     port: 8123
#
# ---
# apiVersion: gateway.networking.k8s.io/v1
# kind: HTTPRoute
# metadata:
#   name: testing-homelab-routes
#   namespace: tailscale-agent
# spec:
#   hostnames: []
#   parentRefs:
#     - group: gateway.networking.k8s.io
#       kind: Gateway
#       name: tailnet-gateway
#       namespace: tailscale-agent
#   rules:
#   - backendRefs:
#     - name: hydra-backend
#       port: 8123
