apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: garage-web
spec:
  parentRefs:
  - name: shared
    namespace: default
  hostnames:
  - cdn.juliamertz.dev
  - nettenshop.cdn.juliamertz.dev
  rules:
  - backendRefs:
    - name: garage
      port: 3902

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: valnetten-web
spec:
  parentRefs:
  - name: shared
    namespace: default
  hostnames:
  - valnetten.preview.juliamertz.dev
  rules:
  - filters:
    - type: URLRewrite
      urlRewrite:
        hostname: valnetten.cdn.juliamertz.dev
    backendRefs:
    - name: garage
      port: 3902

---
apiVersion: cert-vandal.io/v1
kind: SANInjection
metadata:
  name: garage-web
spec:
  targetCertificate:
    name: gateway-tls
    namespace: default
  hostnames:
    - cdn.juliamertz.dev
    - nettenshop.cdn.juliamertz.dev
    - valnetten.preview.juliamertz.dev

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: garage-api
spec:
  parentRefs:
  - name: shared
    namespace: default
  hostnames:
  - s3.juliamertz.dev
  rules:
  - backendRefs:
    - name: garage
      port: 3900

---
apiVersion: cert-vandal.io/v1
kind: SANInjection
metadata:
  name: garage-api
spec:
  targetCertificate:
    name: gateway-tls
    namespace: default
  hostnames:
    - s3.juliamertz.dev
