---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: hetzner-proxy-config
  namespace: envoy-gateway-system
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        type: ClusterIP

# ---
# apiVersion: gateway.envoyproxy.io/v1alpha1
# kind: EnvoyProxy
# metadata:
#   name: hetzner-proxy-config
#   namespace: envoy-gateway-system
# spec:
#   provider:
#     type: Kubernetes
#     kubernetes:
#       envoyService:
#         type: LoadBalancer
#         annotations:
#           load-balancer.hetzner.cloud/protocol: "tcp"
#           load-balancer.hetzner.cloud/use-private-ip: "false"
#           load-balancer.hetzner.cloud/uses-proxyprotocol: "false"
#           load-balancer.hetzner.cloud/algorithm: "round_robin"
#           load-balancer.hetzner.cloud/location: "nbg1"
#           load-balancer.hetzner.cloud/type: "lb11"
