apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: valheim
resources:
  - namespace.yaml
  - volumes.yaml
  - statefulset.yaml
  - scaler.yaml
  - backup.yaml
images:
- name: valheim-server
  newName: lloesche/valheim-server
  newTag: sha-951992b
