apiVersion: v1
kind: Service
metadata:
  name: valheim-server
spec:
  ports:
  - name: gameport
    port: 2456
    targetPort: 2456
    protocol: UDP
    nodePort: 32456
  # - name: queryport
  #   port: 2457
  #   targetPort: 2457
  #   protocol: UDP
  #   nodePort: {{ default "" (.Values.networking.nodePort | int | add 1) }}
  type: NodePort
  # loadBalancerIP: {{ .Values.networking.loadBalancerIP | quote }}
  selector:
    app: valheim-server
