apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: valheim-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: valheim-server
  template:
    metadata:
      labels:
        app: valheim-server
      annotations:
        dns.juliamertz.dev/hostdns: "true"
        dns.juliamertz.dev/hostname: valheim.juliamertz.nl
        dns.juliamertz.dev/delete-after: 24h
        dns.juliamertz.dev/ttl: "60"
    spec:
      terminationGracePeriodSeconds: 120
      nodeSelector:
        hcloud/node-group: gameserver-node
      tolerations:
        - key: node.kubernetes.io/role
          operator: Equal
          value: gameserver-node
          effect: NoExecute
      hostNetwork: true
      containers:
      - image: valheim-server
        imagePullPolicy: IfNotPresent
        name: valheim
        env:
        - name: PORT
          value: "2456"
        - name: NAME
          value: "Julia's server"
        - name: WORLD
          value: "Julia's realm"
        - name: TZ
          value: "Europe/Amsterdam"
        - name: PUBLIC
          value: "1"
        - name: UPDATE_ON_STARTUP
          value: "1"
        - name: HTTP_PORT
          value: "9000"
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: valheim-auth 
              key: password
              optional: false
        ports:
        - containerPort: 2456
          name: gameport
        - containerPort: 2457
          name: queryport
        - containerPort: 9000
          name: metrics
        volumeMounts:
        - mountPath: /home/steam/.config/unity3d/IronGate/Valheim
          name: gamefiles
        - mountPath: /home/steam/valheim
          name: serverfiles
        resources:
          requests: {}
      volumes:
      - name: gamefiles
        persistentVolumeClaim:
          claimName: valheim-world
      - name: serverfiles
        persistentVolumeClaim:
          claimName: valheim-data
