{
 "title": "Garage",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"garage\", container=\"garage\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(container_memory_usage_bytes{namespace=\"garage\", container=\"garage\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Free disk space",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_capacity_bytes{namespace=\"garage\", persistentvolumeclaim=~\"data-garage-\\\\d\"} - kubelet_volume_stats_available_bytes{namespace=\"garage\", persistentvolumeclaim=~\"data-garage-\\\\d\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  }
 ]
}