apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cloudnative-pg
spec:
  interval: 30m
  url: https://cloudnative-pg.github.io/charts

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
spec:
  interval: 5m
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.27.1
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
  values:
    crds:
      create: true
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace


---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: barman-plugin
spec:
  interval: 5m
  chart:
    spec:
      chart: plugin-barman-cloud
      version: 0.4.0
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
  values:
    fullnameOverride: barman-cloud-plugin
    crds:
      create: true
