services:
  - cmd: host-dns

  - cmd: sync
    admin: true
    extraEnv:
      - name: GIT_URL
        value: https://github.com/juliamertz/infra.git
      - name: INTERVAL
        value: "30"
      - name: SOPS_AGE_KEY_FILE
        value: /etc/sops/age/keys.txt
    volumes:
      - name: sops-age-key
        secret:
          secretName: sops-age-key
    volumeMounts:
      - name: sops-age-key
        mountPath: /etc/sops/age
        readOnly: true
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 1000m

  - cmd: cert-approver
    extraEnv:
      - name: INTERNAL_IP_RANGE
        value: 10.0.0.0/8
