services:
  - cmd: host-dns

  - cmd: sync
    admin: true
    logLevel: info
    extraEnv:
      - name: GIT_URL
        value: https://github.com/juliamertz/infra.git
      - name: INTERVAL
        value: "10"
      - name: SOPS_AGE_KEY_FILE
        value: /etc/sops/age/keys.txt
      - name: GITHUB_PAT
        valueFrom:
          secretKeyRef:
            name: sync-controller-secrets
            key: github-pat
    volumes:
      - name: sops-age-key
        secret:
          secretName: sops-age-key
    volumeMounts:
      - name: sops-age-key
        mountPath: /etc/sops/age
        readOnly: true
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 1500m

  - cmd: cert-approver
    extraEnv:
      - name: INTERNAL_IP_RANGE
        value: 10.0.0.0/8
