# WARNING: This cert has been modified by saninjections. not a good idea to re-apply and nuke the cert

# ---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: gateway-tls
# spec:
#   secretName: tls-cert-gateway
#   issuerRef:
#     kind: ClusterIssuer
#     name: letsencrypt-prod
#   dnsNames:
#     - api.vertrouwdbouwen.com
#     - cdn.juliamertz.dev
#     - db.vertrouwd-bouwen.juliamertz.dev
#     - grafana.prod.juliamertz.dev
#     - hass.juliamertz.dev
#     - hass.juliamertz.nl
#     - lightspeed-adapter.juliamertz.dev
#     - merlijnvoncken.com
#     - merlijnvoncken.nl
#     - nettenshop.juliamertz.dev
#     - nettenshop.juliamertz.nl
#     - s3.juliamertz.dev
#     - test.juliamertz.dev
#     - valnetten-test.juliamertz.dev
#     - valnetten.cdn.juliamertz.dev
#     - vertrouwdbouwen.com
#     - watch.juliamertz.dev
#     - watch.juliamertz.nl
