apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: shared
  namespace: default
spec:
  gatewayClassName: envoy
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: tls-cert-gateway
      allowedRoutes:
        namespaces:
          from: All

# ---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: gateway-tls
# spec:
#   secretName: tls-cert-gateway
#   issuerRef:
#     kind: ClusterIssuer
#     name: letsencrypt-prod
#   dnsNames:
#     - test.juliamertz.dev
