apiVersion: v1
kind: ConfigMap
metadata:
  name: attic-config
data:
  server.toml: |
    listen = "0.0.0.0:8080"
    api-endpoint = "https://attic.juliamertz.dev/"

    [database]

    [storage]
    type = "s3"
    endpoint = "http://garage.garage:3900"
    region = "garage"
    bucket = "attic-cache"
    force_path_style = true

    [chunking]
    nar-size-threshold = 65536
    min-size = 16384
    avg-size = 65536
    max-size = 262144

    [compression]
    type = "zstd"
