apiVersion: apps/v1
kind: Deployment
metadata:
  name: attic
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: attic
  template:
    metadata:
      labels:
        app: attic
    spec:
      containers:
        - name: attic
          image: attic
          command: ["atticd", "-f", "/attic/server.toml"]
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: RUST_LOG
              value: debug
            - name: ATTIC_SERVER_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: attic-db-app
                  key: uri
            - name: ATTIC_SERVER_TOKEN_HS256_SECRET_BASE64
              valueFrom:
                secretKeyRef:
                  name: attic-token
                  key: token
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: storage-credentials
                  key: accessKey
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: storage-credentials
                  key: secretKey
          volumeMounts:
            - name: config
              mountPath: /attic/server.toml
              subPath: server.toml
          resources:
            requests:
              memory: "128Mi"
              cpu: "10m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 6
      volumes:
        - name: config
          configMap:
            name: attic-config
