apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: attic
resources:
  - namespace.yml
  - database.yml
  - config.yml
  - secrets.yml
  - deployment.yml
  - service.yml
  - certificate.yml
  - httproute.yml
images:
- name: attic
  newName: ghcr.io/zhaofengli/attic
  newTag: 9736e87439be1b5d40cad1dff004e1d845f8b9e7 
