events {}

http {
  server {
    listen 80;

    location / {
      add_header Access-Control-Allow-Origin * always;
      add_header Access-Control-Allow-Methods "GET, POST, OPTIONS, PUT, DELETE" always;
      add_header Access-Control-Allow-Headers "Authorization, Content-Type, X-Requested-With" always;

      proxy_pass https://api.adsb.lol;
      proxy_ssl_server_name on;
      proxy_set_header Host api.adsb.lol;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_redirect ~^https?://api\.adsb\.lol(/.*)$ https://adsb-proxy.juliamertz.dev$1;
    }
  }
}

