{
 "title": "Nettenshop",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Processed orders",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(lightspeed_dhl_adapter_processed_count{namespace=\"lightspeed-dhl-adapter\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unprocessed orders",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(lightspeed_dhl_adapter_unprocessed_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "group by(instance) (probe_success{instance=\"https://nettenshop.juliamertz.dev/ready\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Webhook logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"webhook\", namespace=\"lightspeed-dhl-adapter\"} |= `` | json"
    }
   ]
  },
  {
   "title": "Webhook memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container=\"webhook\", namespace=\"lightspeed-dhl-adapter\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Cronjob logs",
   "type": "logs",
   "gridPos": { "h": 16, "w": 14, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"poll-status\", namespace=\"lightspeed-dhl-adapter\"} | json"
    },
    {
     "direction": "backward",
     "expr": "{app=\"mark-stale\", namespace=\"lightspeed-dhl-adapter\"} | json"
    }
   ]
  },
  {
   "title": "Cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=\"webhook\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(axum_http_requests_duration_seconds_sum[$__rate_interval])) by (exported_endpoint)\n/\nsum(rate(axum_http_requests_duration_seconds_count[$__rate_interval])) by (exported_endpoint)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateway logs",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{namespace=\"default\", app=\"envoy\"} |= `` | json | route_name =~ `httproute/lightspeed-dhl-adapter/.*` | user_agent !~ `Blackbox-Exporter\\/\\d+\\.\\d+.\\d+` | label_format level=`{{if ge .response_code \"400\"}}ERROR{{else}}INFO{{end}}`"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{namespace=\"lightspeed-dhl-adapter\"} | json | level = `ERROR` | label_format pod=\"hello\"",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}