---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: hetzner-proxy-config
  namespace: envoy-gateway-system
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        type: LoadBalancer
        annotations:
          load-balancer.hetzner.cloud/use-private-ip: "true"
          load-balancer.hetzner.cloud/location: "nbg1"
          load-balancer.hetzner.cloud/algorithm-type: "round_robin"
          load-balancer.hetzner.cloud/name: "envoy-gateway-shared-lb"
          load-balancer.hetzner.cloud/uses-proxyprotocol: "true"
          # load-balancer.hetzner.cloud/node-selector: "!node-role.kubernetes.io/control-plane"
      envoyPDB:
        minAvailable: 3
      envoyDeployment:
        replicas: 3 
        strategy:
          rollingUpdate:
            maxSurge: 1
            maxUnavailable: 0
        pod:
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: envoy
              matchLabelKeys:
                - pod-template-hash
                - gateway.envoyproxy.io/owning-gateway-name
                - gateway.envoyproxy.io/owning-gateway-namespace
      envoyHpa:
        minReplicas: 3
        maxReplicas: 9
        metrics:
          - resource:
              name: cpu
              target:
                averageUtilization: 60
                type: Utilization
            type: Resource
