apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: envoy-ratelimit-db
spec:
  imagePullPolicy: IfNotPresent
  image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.35.1
  replicas: 1
  resources:
    requests:
      memory: 512Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 100m

