apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - metrics-server
  - external-dns
  - envoy-gateway
  - cert-manager
  - cloudnative-pg
  - longhorn
  - dragonfly-operator
