apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - namespace.yaml
  - releases.yaml
  - httproute.yaml

configMapGenerator:
  - name: nettenshop-dashboard
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1" 
    files:
      - dashboards/nettenshop.json

