apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authelia-db
  namespace: authelia
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised
  primaryUpdateMethod: switchover
  enableSuperuserAccess: false
  storage:
    size: 1Gi
    storageClass: longhorn-local
    resizeInUseVolumes: true
  bootstrap:
    initdb:
      database: authelia
      owner: authelia
