apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: authelia-cache
  namespace: authelia
spec:
  replicas: 1
  resources:
    limits:
      cpu: 100m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 512Mi
