apiVersion: v1
kind: Secret
metadata:
  name: authelia-secrets
  namespace: authelia
stringData:

  SESSION_SECRET: "" # generate with: openssl rand -hex 32
  STORAGE_ENCRYPTION_KEY: "" # generate with: openssl rand -hex 32
  USERS_DATABASE: |
    users:
      julia:
        displayname: Julia
        password: <>
        email: info@email.com
        groups:
          - admins
