apiVersion: v1
kind: Secret
metadata:
    name: barman-credentials
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:9Eecc/6hLevIGpUBKA3g50+d2Qs5pKY2vQ==,iv:e7lvgiqPkjE8LdplOwlCNGlbNUahN7mm0NizZps/5RM=,tag:EZkBUYi7d07b+/d8fjy9qw==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:UXqkgUVE9pE2IjDolbujaMscKy0eEwABnEukEio2cw==,iv:WdZxOw93odspb1di4GulJ/ha/tBzCUm4QTbl3EvCsfQ=,tag:jayCNRp/LxSAlbmgJPTePQ==,type:str]
sops:
    age:
        - recipient: age1wu0knmpfys4szjf09cgvc7fq8u34h0dyu9uk6sfzvkmqlklcya6skhmhs5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEaUkzeVMrSzBEVWRpYzFk
            VXAvNXdWVXZiMVpKM0trZ0IrMjVaOGI4ODNZCmlRQ3V6N1JXeGJVVFZWT055dDdr
            QUVXVjNET0RZL1VxZHJpNFdCbTRNbUEKLS0tIC9VeCtCNmpWOVZlNnJrdzJsQWR6
            ck9ZRjFRT1N5cHZOY3FYeWQwWVFuMTgKMhtDL7NnTVyn6zZqpP//ctq+kkJSPeCB
            7r030jf6kpHUUuVrAKMtInXF6puXayP3dLl/lXSGPYAuJY23VjLpBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-11T23:02:38Z"
    mac: ENC[AES256_GCM,data:+kibndnme55cNCqWHcK3Ebf8BNpLRaifiXi+8r/C/nGkbNf+3IWouJQ/EwGbHkg6YDoXe3noOwdmtgP9acRcuv/z0pOs4NT70jmryrJbA5In5FvDTfRina4uecYJuG1plRCZAXehN8q4xc/LRPHKJJ/KJ5HOzwGwF9ofUoCEEuQ=,iv:dkDIAEox+aHXP0Q8k+7pJBg0tXz/WVDihOXeiSsSfJs=,tag:qLsTa/CjR3LGrExVb/ULeA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
